app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::auth();

Route::resource('/', 'User\BerandaController@index');
Route::post('/pengaduan/store', 'User\BerandaController@store');

Route::resource('/profil/visimisi', 'User\ProfilController@visimisi');
Route::resource('/profil/sejarah', 'User\ProfilController@sejarah');
Route::resource('/profil/demografi', 'User\ProfilController@demografi');

Route::resource('/berita', 'User\BeritaController');
Route::get('cari', 'User\BeritaController@cari');

Route::resource('/lembaga/struktur', 'User\StrukturController');
Route::resource('/lembaga/staff', 'User\StaffController');
Route::resource('/lembaga/bpd', 'User\BPDController');
Route::resource('/lembaga/lpmd', 'User\LPMDController');
Route::resource('/lembaga/pkk', 'User\PKKController');
Route::resource('/lembaga/rt', 'User\RTController');
Route::resource('/lembaga/karangtaruna', 'User\KarangTarunaController');

Route::resource('/layanan/perizinan', 'User\LayananController@perizinan');
Route::resource('/layanan/kk', 'User\LayananController@kk');

Route::resource('/gallery', 'User\GalleryController');

//ADMIN
Route::resource('/admin/beranda', 'Admin\WelcomeController');
Route::resource('/admin/berita', 'Admin\BeritaController');
Route::resource('/admin/pengaduan', 'Admin\PengaduanController');
Route::resource('/admin/komentar', 'Admin\KomentarController');
Route::resource('/admin/gallery', 'Admin\GalleryController');

Route::resource('/admin/lembaga/staff', 'Admin\StaffController');
Route::resource('/admin/lembaga/bpd', 'Admin\BPDController');
Route::resource('/admin/lembaga/lpmd', 'Admin\LPMDController');
Route::resource('/admin/lembaga/rt', 'Admin\RTController');
Route::resource('/admin/lembaga/karangtaruna', 'Admin\KarangTarunaController');
Route::resource('/admin/lembaga/pkk', 'Admin\PKKController');

Route::resource('/admin/pengaturan', 'Admin\PengaturanController');
Route::resource('/admin/pengaturan/kontak', 'Admin\KontakController');
Route::resource('/admin/info', 'Admin\MetaController');
Route::resource('/admin/banner', 'Admin\BannerController');

resources/views/admin/lembaga/bpd.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Badan Permusyawaratan Daerah
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tambah Data BPD</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.lembaga.bpd.store', 'class'=>'form-horizontal'])!!}
                          @include('form._admin_bpd')
                        {!! Form::close() !!}
                    </div>
                </div>

                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Data BPD</h3>
                    </div>
                        <div class="box-body" style="overflow-x:auto;">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <td>No</td>
                                    <td>Nama</td>
                                    <td>Jabatan</td>
                                    <td>Keterangan</td>
                                    <td colspan="2" align="center">Action</td>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($bpd as $item)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $item->nama }}</td>
                                        <td>{{ $item->jab->jabatan }} {{$item->jabatan }}</td>
                                        <td>{{ $item->keterangan}}</td>
                                        <td>
                                        <div class="col-md-12">
                                            <div class="col-md-6">
                                                <a href="{{ route('admin.lembaga.bpd.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                            </div>
                                            <div class="col-md-6">
                                                {{ Form::open(['route' => ['admin.lembaga.bpd.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                                    {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                                {{ Form::close() }}
                                            </div>
                                        </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/lembaga/edit_bpd.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Badan Permusyawaratan Daerah
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Data BPD</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($bpd, ['route' => ['admin.lembaga.bpd.update', $bpd],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_bpd', ['model' => $bpd])
                        {!! Form::close() !!}
                    </div>
                </div>

            </div>
        </div>
    </section>
@endsection

resources/views/admin/lembaga/edit_lpmd.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Lembaga Pemberdayaan Masyarakat Desa
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Data LPMD</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($lpmd, ['route' => ['admin.lembaga.lpmd.update', $lpmd],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_bpd', ['model' => $lpmd])
                        {!! Form::close() !!}
                    </div>
                </div>

            </div>
        </div>
    </section>
@endsection

resources/views/admin/lembaga/edit_pkk.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Pemberdayaan Kesejahteraan Keluarga 
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Data PKK</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($pkk, ['route' => ['admin.lembaga.pkk.update', $pkk],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_bpd', ['model' => $pkk])
                        {!! Form::close() !!}
                    </div>
                </div>

            </div>
        </div>
    </section>
@endsection

resources/views/admin/lembaga/edit_rt.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Rukun Tetangga
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Data RT</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($rt, ['route' => ['admin.lembaga.rt.update', $rt],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_rt', ['model' => $rt])
                        {!! Form::close() !!}
                    </div>
                </div>

            </div>
        </div>
    </section>
@endsection

resources/views/admin/lembaga/edit_staff.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Staff
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Data Staff</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($staff, ['route' => ['admin.lembaga.staff.update', $staff],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_staff', ['model' => $staff])
                        {!! Form::close() !!}
                    </div>
                </div>

            </div>
        </div>
    </section>
@endsection

resources/views/admin/lembaga/edit_taruna.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Karang Taruna
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Edit Data Karang Taruna</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($taruna, ['route' => ['admin.lembaga.karangtaruna.update', $taruna],'method' =>'patch','class'=>'form-horizontal'])!!}
                            @include('form._admin_bpd', ['model' => $taruna])
                        {!! Form::close() !!}
                    </div>
                </div>

            </div>
        </div>
    </section>
@endsection

resources/views/admin/lembaga/lpmd.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Lembaga Pemberdayaan Masyarakat Desa
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tambah Data LPMD</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.lembaga.lpmd.store', 'class'=>'form-horizontal'])!!}
                          @include('form._admin_bpd')
                        {!! Form::close() !!}
                    </div>
                </div>

                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Data LPMD</h3>
                    </div>
                        <div class="box-body" style="overflow-x:auto;">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <td>No</td>
                                    <td>Nama</td>
                                    <td>Jabatan</td>
                                    <td>Keterangan</td>
                                    <td colspan="2" align="center">Action</td>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($lpmd as $item)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $item->nama }}</td>
                                        <td>{{ $item->jab->jabatan }} {{$item->jabatan }}</td>
                                        <td>{{ $item->keterangan}}</td>
                                        <td>
                                        <div class="col-md-12">
                                            <div class="col-md-6">
                                                <a href="{{ route('admin.lembaga.lpmd.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                            </div>
                                            <div class="col-md-6">
                                                {{ Form::open(['route' => ['admin.lembaga.lpmd.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                                    {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                                {{ Form::close() }}
                                            </div>
                                        </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/lembaga/pkk.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Pemberdayaan Kesejahteraan Keluarga 
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tambah Data PKK</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.lembaga.pkk.store', 'class'=>'form-horizontal'])!!}
                          @include('form._admin_bpd')
                        {!! Form::close() !!}
                    </div>
                </div>

                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Data PKK</h3>
                    </div>
                        <div class="box-body" style="overflow-x:auto;">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <td>No</td>
                                    <td>Nama</td>
                                    <td>Jabatan</td>
                                    <td>Keterangan</td>
                                    <td colspan="2" align="center">Action</td>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($pkk as $item)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $item->nama }}</td>
                                        <td>{{ $item->jab->jabatan }} {{$item->jabatan }}</td>
                                        <td>{{ $item->keterangan}}</td>
                                        <td>
                                        <div class="col-md-12">
                                            <div class="col-md-6">
                                                <a href="{{ route('admin.lembaga.pkk.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                            </div>
                                            <div class="col-md-6">
                                                {{ Form::open(['route' => ['admin.lembaga.pkk.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                                    {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                                {{ Form::close() }}
                                            </div>
                                        </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/lembaga/rt.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Rukun Tetangga
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tambah Data RT</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.lembaga.rt.store', 'class'=>'form-horizontal'])!!}
                          @include('form._admin_rt')
                        {!! Form::close() !!}
                    </div>
                </div>

                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Data RT</h3>
                    </div>
                        <div class="box-body" style="overflow-x:auto;">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <td>No</td>
                                    <td>RW</td>
                                    <td>RT</td>
                                    <td>Nama</td>
                                    <td>Jabatan</td>
                                    <td>Keterangan</td>
                                    <td colspan="2" align="center">Action</td>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($rt as $item)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $item->rw }}</td>
                                        <td>{{ $item->rt }}</td>
                                        <td>{{ $item->nama }}</td>
                                        <td>{{ $item->jab->jabatan }} {{$item->jabatan }}</td>
                                        <td>{{ $item->keterangan}}</td>
                                        <td>
                                        <div class="col-md-12">
                                            <div class="col-md-6">
                                                <a href="{{ route('admin.lembaga.rt.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                            </div>
                                            <div class="col-md-6">
                                                {{ Form::open(['route' => ['admin.lembaga.rt.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                                    {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                                {{ Form::close() }}
                                            </div>
                                        </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/lembaga/staff.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Staff
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tambah Data Staff</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.lembaga.staff.store', 'class'=>'form-horizontal'])!!}
                          @include('form._admin_staff')
                        {!! Form::close() !!}
                    </div>
                </div>

                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Data Staff</h3>
                    </div>
                        <div class="box-body" style="overflow-x:auto;">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <td>No</td>
                                    <td>Nama</td>
                                    <td>Jabatan</td>
                                    <td>No SK Jabatan</td>
                                    <td colspan="2" align="center">Action</td>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($staff as $item)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $item->nama }}</td>
                                        <td>{{ $item->jab->jabatan }} {{$item->jabatan }}</td>
                                        <td>{{ $item->sk}}</td>
                                        <td>
                                        <div class="col-md-12">
                                            <div class="col-md-6">
                                                <a href="{{ route('admin.lembaga.staff.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                            </div>
                                            <div class="col-md-6">
                                                {{ Form::open(['route' => ['admin.lembaga.staff.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                                    {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                                {{ Form::close() }}
                                            </div>
                                        </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/lembaga/taruna.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Karang Taruna 
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tambah Data Karang Taruna</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.lembaga.karangtaruna.store', 'class'=>'form-horizontal'])!!}
                          @include('form._admin_bpd')
                        {!! Form::close() !!}
                    </div>
                </div>

                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Data Karang Taruna</h3>
                    </div>
                        <div class="box-body" style="overflow-x:auto;">
                            <table class="table table-bordered">
                                <thead>
                                <tr>
                                    <td>No</td>
                                    <td>Nama</td>
                                    <td>Jabatan</td>
                                    <td>Keterangan</td>
                                    <td colspan="2" align="center">Action</td>
                                </tr>
                                </thead>
                                <tbody>

                                @foreach($taruna as $item)
                                    <tr>
                                        <td>{{ $no++ }}</td>
                                        <td>{{ $item->nama }}</td>
                                        <td>{{ $item->jab->jabatan }} {{$item->jabatan }}</td>
                                        <td>{{ $item->keterangan}}</td>
                                        <td>
                                        <div class="col-md-12">
                                            <div class="col-md-6">
                                                <a href="{{ route('admin.lembaga.karangtaruna.edit', $item->id) }}" class="btn btn-primary">Ubah</a>
                                            </div>
                                            <div class="col-md-6">
                                                {{ Form::open(['route' => ['admin.lembaga.karangtaruna.destroy' , $item->id] ,'method' => 'DELETE']) }}
                                                    {{ Form::submit('Hapus', ['class' => 'btn btn-danger js-submit-confirm']) }}
                                                {{ Form::close() }}
                                            </div>
                                        </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection