app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::auth();

Route::resource('/', 'User\BerandaController@index');
Route::post('/pengaduan/store', 'User\BerandaController@store');

Route::resource('/profil/visimisi', 'User\ProfilController@visimisi');
Route::resource('/profil/sejarah', 'User\ProfilController@sejarah');
Route::resource('/profil/demografi', 'User\ProfilController@demografi');

Route::resource('/berita', 'User\BeritaController');
Route::get('cari', 'User\BeritaController@cari');

Route::resource('/lembaga/struktur', 'User\StrukturController');
Route::resource('/lembaga/staff', 'User\StaffController');
Route::resource('/lembaga/bpd', 'User\BPDController');
Route::resource('/lembaga/lpmd', 'User\LPMDController');
Route::resource('/lembaga/pkk', 'User\PKKController');
Route::resource('/lembaga/rt', 'User\RTController');
Route::resource('/lembaga/karangtaruna', 'User\KarangTarunaController');

Route::resource('/layanan/perizinan', 'User\LayananController@perizinan');
Route::resource('/layanan/kk', 'User\LayananController@kk');

Route::resource('/gallery', 'User\GalleryController');

//ADMIN
Route::resource('/admin/beranda', 'Admin\WelcomeController');
Route::resource('/admin/berita', 'Admin\BeritaController');
Route::resource('/admin/pengaduan', 'Admin\PengaduanController');
Route::resource('/admin/komentar', 'Admin\KomentarController');
Route::resource('/admin/gallery', 'Admin\GalleryController');

Route::resource('/admin/lembaga/staff', 'Admin\StaffController');
Route::resource('/admin/lembaga/bpd', 'Admin\BPDController');
Route::resource('/admin/lembaga/lpmd', 'Admin\LPMDController');
Route::resource('/admin/lembaga/rt', 'Admin\RTController');
Route::resource('/admin/lembaga/karangtaruna', 'Admin\KarangTarunaController');
Route::resource('/admin/lembaga/pkk', 'Admin\PKKController');

Route::resource('/admin/pengaturan', 'Admin\PengaturanController');
Route::resource('/admin/pengaturan/kontak', 'Admin\KontakController');
Route::resource('/admin/info', 'Admin\MetaController');
Route::resource('/admin/banner', 'Admin\BannerController');

app/Berita.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Berita extends Model
{
    protected $table = 'beritas';

    protected $fillable = [
        'judul','isi','photo',
    ];

    // relasi one to many ke komentar
    public function komentar()
    {
        return $this->hasMany('App\Komentar');
    }
}

app/Http/Controllers/Admin/BeritaController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;

use App\Berita;
use App\Komentar;

class BeritaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    
    
    public function index(Request $request)
    {
        $page = $request->get('page');

        $no = 1;

        if($page>1){
            $no = $page * 10 - 9;
        }else{
            $no=1;
        }

        $berita = Berita::orderBy('id','DESC')->paginate(10);

        return view('admin.berita.berita', compact('berita','no'));
    }

    public function create()
    {
        return view('admin.berita.tambahberita');
    }

    public function store(Request $request)
    {
        // SIMPAN DATA SISWA META
        $berita = $request->only('judul','isi');

        if ($request->hasFile('photo')) {
            $berita['photo'] = $this->savePhoto($request->file('photo'));
        } else {
            $berita['photo'] = '-';
        }

        Berita::create($berita);

        $notification = array(
            'message' => 'Berita berhasil ditambah.',
            'alert-type' => 'success'
        );
        return redirect()->route('admin.berita.index')->with($notification);
    }

    public function show($id)
    {
        $berita = Berita::findOrFail($id);

        return view('admin.berita.show_berita', compact('berita'));
    }

    public function edit($id)
    {
        $berita = Berita::findOrFail($id);
        return view('admin.berita.edit_berita', compact('berita'));
    }

    public function update(Request $request, $id)
    {
        $berita = Berita::findOrFail($id);

        // SIMPAN DATA SISWA META
        $databerita = $request->only('judul','isi');

        if ($request->hasFile('photo')) {
            $this->deletePhoto($berita->photo);
            $databerita['photo'] = $this->savePhoto($request->file('photo'));
        }

        $berita->update($databerita);
        $notification = array(
            'message' => 'Berita berhasil diubah.',
            'alert-type' => 'info'
        );
        return redirect()->route('admin.berita.index')->with($notification);
    }

    public function destroy($id)
    {
        $hapus = Berita::findOrFail($id);

        $berita = Berita::find($id);
        $this->deletePhoto($berita->photo);
  
        $notification = array(
            'message' => 'Berita berhasil dihapus.',
            'alert-type' => 'error'
        );
        
        Berita::find($id)->delete();
        Komentar::where('berita_id',$id)->delete();
        return redirect()->route('admin.berita.index')->with($notification);
    }

    protected function savePhoto(UploadedFile $photo)
    {
      $fileName = str_random(40) . '.' . $photo->guessClientExtension();
      $destinationPath = 'itlabil/images/berita';
      $photo->move($destinationPath, $fileName);
      return $fileName;
    }

    public function deletePhoto($filename)
    {
      $path = 'itlabil/images/berita/'.$filename;
      return File::delete($path);
    }
}

app/Http/Controllers/User/BeritaController.php
<?php

namespace App\Http\Controllers\User;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Berita;
use App\kontak;
use App\Komentar;
class BeritaController extends Controller
{
    
    public function index()
    {
        $kontak = kontak::where('id',1)->get()->first();
        $berita = Berita::orderBy('id','DESC')->paginate(6);

        return view('user.berita.berita',compact('berita','kontak'));
    }

    public function cari(Request $request)
    {
        $kontak = kontak::where('id',1)->get()->first();
        $cari = $request->get('cari');

        $berita = Berita::Where('isi', 'LIKE', '%'.$cari.'%')
                    ->orderBy('id','DESC')->paginate(6);
        
        return view('user.berita.cari_berita', compact('berita','cari','kontak'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $komentar = $request->only('berita_id','nama','email','komentar');

        Komentar::create($komentar);

        $notification = array(
            'message' => 'Komentar berhasil dikirim.',
            'alert-type' => 'success'
        );

        return redirect('berita/'.$request->get('berita_id'))->with($notification);
    }

    public function show($id)
    {
        $kontak = kontak::where('id',1)->get()->first();
        $berita = Berita::findOrFail($id);
        $beritalain = Berita::where('id', 'NOT LIKE',$id)
                ->orderBy('id','DESC')
                ->paginate(5);

        $komentar = Komentar::where('berita_id', $id)
                ->orderBy('id','DESC')
                ->paginate(10);

        return view('user.berita.show_berita', compact('berita','kontak','beritalain','komentar'));
    }

    public function edit($id)
    {
        //
    }

    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/berita/berita.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Berita
        </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Data Berita</h3>
                    </div>
                    <div class="box-body" style="overflow-x:auto;">

                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <td>No</td>
                                <td>Judul Berita</td>
                                <td colspan="3" align="center">Action</td>
                            </tr>
                            </thead>
                            <tbody>

                            @foreach($berita as $item)
                                <tr>
                                    <td>{{ $no++ }}</td>
                                    <td>{{ $item->judul }}</td>
                                    <td>
                                        <div class="col-md-12">
                                            <div class="col-md-6">
                                                <a href="{{ route('admin.berita.show', $item->id) }}" class="btn btn-primary">Lihat</a>
                                            </div>
                                            <div class="col-md-6">
                                                {!! Form::model($item, ['route' => ['admin.berita.destroy', $item], 'method' => 'delete', 'class' => 'form-inline'] ) !!}
                                                  {!! Form::submit('Hapus', ['class'=>'btn btn-danger js-submit-confirm']) !!}
                                                {!! Form::close()!!}
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $berita->appends(compact('page'))->links() }}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/berita/edit_berita.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Berita
        </h1>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ubah Berita</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::model($berita, ['route' => ['admin.berita.update', $berita],'method' =>'patch','class'=>'form-horizontal','files'=>true])!!}
                            @include('form._admin_berita', ['model' => $berita])
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/berita/show_berita.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Berita
        </h1>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{ $berita->judul }}</h3>
                    </div>
                    <div class="box-body">
                        @if($berita->photo==="-")
                        @else
                            <center><img src="../../itlabil/images/berita/{{ $berita->photo }}" width="600" class="img-thumbnail" alt=""></center><br>
                        @endif
                        {!! $berita->isi !!}
                    </div>
                    <div class="box-body" align="right">
                        <a href="{{ url('admin/berita') }}" class="btn btn-primary">Kembali</a>
                        <a href="{{ route('admin.berita.edit', $berita->id) }}" class="btn btn-success">Ubah</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/berita/tambahberita.blade.php
@extends('layouts.app')

@section('content')

    <section class="content-header">
        <h1>
            Berita
        </h1>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-md-12">

                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Tambah Berita</h3>
                    </div>
                    <div class="box-body">
                        {!! Form::open(['route' => 'admin.berita.store', 'class'=>'form-horizontal','files'=>true])!!}
                            @include('form._admin_berita_tambah')
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection